version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/action
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
      runas: ubuntu
