 name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-1
  S3_BUCKET_NAME: yumi-photo
  CODE_DEPLOY_APPLICATION_NAME: yumiphotography
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: yumi_photography_EC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Authenticate AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ env.AWS_REGION }}

      - name: Package application
        run: |
          # Replace this with your application packaging command
          zip -r app.zip .

      - name: Upload application to S3
        run: |
          aws s3 cp app.zip s3://${{ env.S3_BUCKET_NAME }}/

      - name: Create deployment
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ env.S3_BUCKET_NAME }},key=app.zip
