# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]


env:
  AWS_REGION: us-east-2
  S3_BUCKET_NAME: yumiphoto
  CODE_DEPLOY_APPLICATION_NAME: yumiphoto
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: yumiphoto-deploy

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - name: Create .env file
      run: |
        touch .env
        echo PORT=${{ secrets.PORT }} >> .env
        echo DB_URL=${{ secrets.DB_URL }} >> .env
        cat .env

